unique_ids:
  assets:
    standard-page.html: RTLA5R5P3U74HWL34BHDPWAJKR7PII62
    theme.css: X4AWMWCZX7KV5KOARIXTQRWURVWZZVRT
  forms:
    Form1: 73TDWVB7RFEOGYWOL2CJBVFDPFWUSMMA
  modules: {}
  scripts: {}
  server_modules: {}
